module.exports = {
  mode: "jit",
  purge: [
    "./public/**/*.html",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./common/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontWeight: {
        "extra-bold": 800,
        black: 800,
      },
    },
    container: {
      center: true,
      padding: "1rem",
    },
    colors: {
      transparent: "transparent",
      black: "#333333",
      current: "currentColor",
      dark: "#1F1F1F",
      theme: "#0085FF",
      themeHover: "#2797FE",
      themePress: "#13538D",
      themeDark: "#0D3C67",
      white: "#FFFFFF",
      light: "#EFEFEF",
      lightest: "#9a9a9a",
      lightDark: "#333333",
      red: "#EF373EE5",
    },
    minHeight: {
      0: "0",
      25: "25vh",
      50: "50vh",
      75: "75vh",
      100: "100vh",
      full: "100%",
    },
    screens: {
      xs: "375px",
      sm: "480px",
      md: "768px",
      lg: "993px",
      xl: "1199px",
      xxl: "1400px",
    },
    letterSpacing: {
      tightest: "-.075em",
      tighter: "-.05em",
      tight: "-.025em",
      normal: "0",
      wide: ".025em",
      wider: ".05em",
      widest: ".1em",
      semi: "0.20em",
    },
  },
  variants: {
    extend: {
      marginBottom: ["last"],
    },
    container: ["responsive"],
    display: ["responsive"],
    flex: ["responsive"],
    fontSize: ["responsive"],
    gap: ["responsive"],
    height: ["responsive"],
    margin: ["responsive"],
    padding: ["responsive"],
    textAlign: ["responsive"],
    width: ["responsive"],
    backgroundColor: ["hover"],
    color: ["hover"],
  },
};
